<?php

/**
 * Action Events 
 * 
 * A class generated by Frapi
 * 
 * @link http://getfrapi.com
 * @author Frapi <frapi@getfrapi.com>
 * @link /events
 */
require_once(CUSTOM_LIBRARY . DIRECTORY_SEPARATOR . 'common/libraries.php');

#class Action_Events extends Frapi_Action implements Frapi_Action_Interface
class Action_Events extends Extend_Interface implements Frapi_Action_Interface
{

    /**
     * Required parameters
     * 
     * @var An array of required parameters.
     */
    protected $requiredParams = array();

    /**
     * The data container to use in toArray()
     * 
     * @var A container of data to fill and return in toArray()
     */
    public $data = array();

    public $table = "Events";

    public $name = 'events';

    public $PDefault = Array("id"=>"",
                             "timestamp"=>"",
                             "comment"=>"",
                             "device_id"=>"",
                             "device_name"=>"",
                             "value"=>"",
                             "deleted"=>0,
                             "date_created"=>"",
                             );


    /**
     * To Array
     * 
     * This method returns the value found in the database 
     * into an associative array.
     * 
     * @return array
     */
    public function toArray()
    {
        return $this->data;
    }

    /**
     * Default Call Method
     * 
     * This method is called when no specific request handler has been found
     * 
     * @return array
     */
    public function executeAction()
    {
        return $this->toArray();
    }

    /**
     * Get Request Handler
     * 
     * This method is called when a request is a GET
     * 
     * @return array
     */
    public function executeGet()
    {
        $Params = $this->getParams();
        //print_r($Params);
        if ( array_key_exists("filter", $Params) ) {
            $WhereClause = $Params["filter"];
        } else {
            $WhereClause = "";
        }
        list($this->data['content'][$this->name], $this->data['sql']) = $this->CommonSelect($WhereClause);

        $TData = Array();
        $TData = $this->data['content'][$this->name];
        $CDData = $this->CommonRelated($TData, "Devices", "name", "id", "device_id", "device_name");
        $this->data['content'][$this->name] = $CDData;

        return $this->toArray();
    }

    /**
     * Post Request Handler
     * 
     * This method is called when a request is a POST
     * 
     * @return array
     */
    public function executePost()
    {
        $POverride = Array();
        $POverride["date_created"] = gmdate("Y-m-d H:i:s");

        $Params = $this->getParams();
        if ( ! array_key_exists("timestamp", $Params) ) {
            $Timestamp = time();
            $POverride["timestamp"] = (int)$Timestamp;
        }

        #print_r($POverride);

        $this->data['content'] = $this->CommonChange(null, $POverride, $this->PDefault);

        $TData = Array();
        $TData[] = $this->data['content'][$this->name];
        $CDData = $this->CommonRelated($TData,"Devices", "name", "id", "device_id", "device_name");
        $this->data['content'][$this->name] = $CDData[0];

        return $this->toArray();
    }

    /**
     * Put Request Handler
     * 
     * This method is called when a request is a PUT
     * 
     * @return array
     */
    public function executePut()
    {
        return $this->toArray();
    }

    /**
     * Delete Request Handler
     * 
     * This method is called when a request is a DELETE
     * 
     * @return array
     */
    public function executeDelete()
    {
        return $this->toArray();
    }

    /**
     * Head Request Handler
     * 
     * This method is called when a request is a HEAD
     * 
     * @return array
     */
    public function executeHead()
    {
        return $this->toArray();
    }


}

